apiVersion: apps/v1
kind: Deployment

metadata:
  name: image-pod-1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-container-1

  template:
    metadata:
      labels:
        app: kube-container-1

    spec:
      containers:
        - name: kube-container-1
          image: "northamerica-northeast1-docker.pkg.dev/kubernetes-5409/docker-container/container-1-image"
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: kube-storage
              mountPath: /pratik_PV_dir

      volumes:
        - name: kube-storage
          persistentVolumeClaim:
            claimName: kube-storage
