apiVersion: v1
kind: Service

metadata:
  name: container1-service

spec:
  selector:
    app: kube-container-1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer
